[package]
name = "hyper_demo"
version = "0.1.0"
edition = "2025"

[dependencies]
hyper = { version = "0.14", features = ["client", "tcp", "http1", "http2"] }
tokio = { version = "1", features = ["full"] }
hyper-tls = "0.5"